// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "Аутентифицирует пользователя и возвращает JWT токен",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход пользователя",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный вход",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.AuthResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Неверные данные",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные учетные данные",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Валидирует выход пользователя (на клиенте удаляется токен)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход пользователя",
                "responses": {
                    "200": {
                        "description": "Успешный выход",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает информацию о пользователе из JWT токена",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Информация о текущем пользователе",
                "responses": {
                    "200": {
                        "description": "Информация о пользователе",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.UserResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "Создает нового пользователя и возвращает JWT токен",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешная регистрация",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.AuthResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Неверные данные",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Пользователь уже существует",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Проверяет, что сервис работает",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Проверка здоровья",
                "responses": {
                    "200": {
                        "description": "Сервис работает",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/avatar": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Загружает аватар пользователя и обновляет профиль",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Загрузка аватара",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Avatar file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Avatar URL",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/words": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список слов пользователя с курсорной пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Получить список слов",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Лимит слов (макс. 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Курсор для пагинации",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список слов",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.WordsListResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создает новое слово в словаре пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Создать слово",
                "parameters": [
                    {
                        "description": "Данные слова",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.WordCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Слово создано",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.WordResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Неверные данные",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Импортирует слова из CSV формата. Формат: jp;ru;on;kun;ex_jp;ex_ru;tags. Поля разделены точкой с запятой, массивы внутри полей разделены запятой.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Импорт слов из CSV",
                "parameters": [
                    {
                        "description": "CSV данные для импорта",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.CSVImportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Результат импорта",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.CSVImportResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Неверный формат CSV",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Выполняет поиск слов по различным критериям",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Поиск слов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поисковый запрос (подстрока в jp или ru)",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Теги (точное совпадение)",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Онъёми (точное совпадение)",
                        "name": "on",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Кунъёми (точное совпадение)",
                        "name": "kun",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Лимит слов",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Курсор для пагинации",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Результаты поиска",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.WordsListResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/words/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает слово по ID с проверкой владельца",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Получить слово по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID слова",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Слово",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.WordResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Неверный ID слова",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Слово не найдено",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет слово по ID с проверкой владельца",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Удалить слово",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID слова",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Слово удалено"
                    },
                    "400": {
                        "description": "Неверный ID слова",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Слово не найдено",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет существующее слово (частичное обновление).\nВсе поля опциональны: если поле не передано, оно сохраняет текущее значение.\nПередача пустого массива [] очищает поле.\nПередача null или отсутствие поля оставляет значение без изменений.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Обновить слово",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID слова",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновленные данные (все поля опциональны)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.WordUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Слово обновлено",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.WordResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Неверные данные или пустой запрос",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Слово не найдено",
                        "schema": {
                            "$ref": "#/definitions/jp-ru-dict_backend_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "jp-ru-dict_backend_internal_model.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/jp-ru-dict_backend_internal_model.User"
                }
            }
        },
        "jp-ru-dict_backend_internal_model.AuthResponseWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/jp-ru-dict_backend_internal_model.AuthResponse"
                }
            }
        },
        "jp-ru-dict_backend_internal_model.CSVImportRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "jp-ru-dict_backend_internal_model.CSVImportResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "failed_count": {
                    "type": "integer"
                },
                "imported_count": {
                    "type": "integer"
                }
            }
        },
        "jp-ru-dict_backend_internal_model.CSVImportResponseWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/jp-ru-dict_backend_internal_model.CSVImportResponse"
                }
            }
        },
        "jp-ru-dict_backend_internal_model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "jp-ru-dict_backend_internal_model.User": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "jp-ru-dict_backend_internal_model.UserLoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "jp-ru-dict_backend_internal_model.UserRegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "jp-ru-dict_backend_internal_model.UserResponseWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/jp-ru-dict_backend_internal_model.User"
                }
            }
        },
        "jp-ru-dict_backend_internal_model.Word": {
            "type": "object",
            "required": [
                "jp",
                "ru"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "ex_jp": {
                    "type": "array",
                    "maxItems": 3,
                    "items": {
                        "type": "string"
                    }
                },
                "ex_ru": {
                    "type": "array",
                    "maxItems": 3,
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "jp": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "kun": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "on": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ru": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "tags": {
                    "type": "array",
                    "maxItems": 5,
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "jp-ru-dict_backend_internal_model.WordCreateRequest": {
            "type": "object",
            "required": [
                "jp",
                "ru"
            ],
            "properties": {
                "ex_jp": {
                    "type": "array",
                    "maxItems": 3,
                    "items": {
                        "type": "string"
                    }
                },
                "ex_ru": {
                    "type": "array",
                    "maxItems": 3,
                    "items": {
                        "type": "string"
                    }
                },
                "jp": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "kun": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "on": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ru": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "tags": {
                    "type": "array",
                    "maxItems": 5,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "jp-ru-dict_backend_internal_model.WordResponseWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/jp-ru-dict_backend_internal_model.Word"
                }
            }
        },
        "jp-ru-dict_backend_internal_model.WordUpdateRequest": {
            "type": "object",
            "properties": {
                "ex_jp": {
                    "type": "array",
                    "maxItems": 3,
                    "items": {
                        "type": "string"
                    }
                },
                "ex_ru": {
                    "type": "array",
                    "maxItems": 3,
                    "items": {
                        "type": "string"
                    }
                },
                "jp": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "kun": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "on": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ru": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "tags": {
                    "type": "array",
                    "maxItems": 5,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "jp-ru-dict_backend_internal_model.WordsListResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "next_cursor": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "words": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/jp-ru-dict_backend_internal_model.Word"
                    }
                }
            }
        },
        "jp-ru-dict_backend_internal_model.WordsListResponseWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/jp-ru-dict_backend_internal_model.WordsListResponse"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "JP-RU Dictionary API",
	Description:      "API для личного русско-японского словаря",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
